// TestSupport.swift
// ::rtemis-afm::
// 2026- EDG rtemis.org

import Foundation
import FoundationModels
import XCTest
@testable import RtemisAFM

/// Loads a JSON fixture from `Tests/RtemisAFMTests/Fixtures`.
///
/// `Bundle.module` is generated by SwiftPM for targets that declare
/// `resources:` in `Package.swift`.
func fixture(_ name: String) throws -> JSONValue {
    let url = try XCTUnwrap(Bundle.module.url(forResource: name, withExtension: "json", subdirectory: "Fixtures"))
    return try JSONDecoder().decode(JSONValue.self, from: Data(contentsOf: url))
}

/// Decodes a wire request from JSON text.
func decodeRequest(_ json: String) throws -> ChatCompletionRequest {
    try JSONDecoder().decode(ChatCompletionRequest.self, from: Data(json.utf8))
}

/// The JSON form of a `GenerationSchema`, for asserting on what the
/// converter built. The framework encodes its own dialect (with `title`
/// and `x-order`), which is close enough to JSON Schema to inspect.
func encoded(_ schema: GenerationSchema) throws -> JSONValue {
    let raw = try JSONDecoder().decode(JSONValue.self, from: JSONEncoder().encode(schema))
    let defs = raw["$defs"]?.objectValue ?? [:]
    return inlineRefs(raw, defs: defs, depth: 0)
}

/// Replaces `{"$ref": "#/$defs/X"}` with the definition, a few levels deep
/// (enough for assertions; recursive schemas stop at `depth` 8).
private func inlineRefs(_ node: JSONValue, defs: [String: JSONValue], depth: Int) -> JSONValue {
    guard depth < 8 else { return node }
    switch node {
    case .object(var object):
        if let ref = object["$ref"]?.stringValue, ref.hasPrefix("#/$defs/"), let target = defs[String(ref.dropFirst(8))] {
            return inlineRefs(target, defs: defs, depth: depth + 1)
        }
        for (key, value) in object where key != "$defs" {
            object[key] = inlineRefs(value, defs: defs, depth: depth + 1)
        }
        return .object(object)
    case .array(let items):
        return .array(items.map { inlineRefs($0, defs: defs, depth: depth + 1) })
    default:
        return node
    }
}

/// A scripted `ChatBackend` for server tests: no model needed.
struct FakeBackend: ChatBackend {
    var events: [ChatEvent] = [.contentDelta("Hello"), .contentDelta(", world"), .finished(.stop, Usage(promptTokens: 5, completionTokens: 2))]
    /// Thrown instead of producing events.
    var failure: BridgeError?
    /// Thrown after `failAfter` events have been yielded (mid-stream error).
    var failAfter: Int?
    var modelStatus = ModelStatus(available: true, contextWindow: 8192, capabilities: ["chat", "streaming", "structured_output", "tools"])

    func status() -> ModelStatus { modelStatus }

    func complete(_ request: ChatCompletionRequest) -> AsyncThrowingStream<ChatEvent, any Error> {
        AsyncThrowingStream { continuation in
            if let failure {
                continuation.finish(throwing: failure)
                return
            }
            for (index, event) in events.enumerated() {
                if let failAfter, index == failAfter {
                    continuation.finish(throwing: BridgeError.serverError("boom"))
                    return
                }
                continuation.yield(event)
            }
            continuation.finish()
        }
    }
}

/// Splits an SSE body into its `data:` payloads.
func sseData(_ body: String) -> [String] {
    body.split(separator: "\n\n").compactMap { block in
        let line = block.trimmingCharacters(in: .whitespacesAndNewlines)
        return line.hasPrefix("data: ") ? String(line.dropFirst(6)) : nil
    }
}
